# Site settings
title: 기록하는 개발자
SEOTitle: 기록하는 개발자 | Seungmi Blog
header-img: img/bg0.jpg
email: yessm621@gmail.com
description: "공부하면서 배운 내용을 기록합니다."
keyword: "Spring, JPA, Java, Django, Python, Git, CS"
url: "https://yessm621.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
# weibo_username: yessm621
# zhihu_username: yessm621
github_username: yessm621
# twitter_username: yessm621
#facebook_username:  yessm621
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: yessm621

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
google_analytics: G-D7YTVDV156

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Spring/Java BackEnd 개발자"
sidebar-avatar: "./img/Uja.JPG" # use absolute URL, seeing it's used in both `/` and `/about/`

# Navbar
navbar-links:
  About: "about"
  Archives: "/archive"

# Featured Tags 
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
# friends:
#   [
#     { title: "乱序（Midare）", href: "http://mida.re/" },
#     { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#     { title: "Kun Qian", href: "http://kunq.me" },
#     { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#     { title: "SmdCn", href: "http://blog.smdcn.net" },
#     { title: "JiyinYiyong", href: "http://tiye.me/" },
#     { title: "DHong Say", href: "http://dhong.co" },
#     { title: "尹峰以为", href: "http://ingf.github.io/" },
#   ]
